language: r
cache: packages
latex: false
r:
  #- 3.2.5
  #- 3.3.3
  - 3.4.4
  #- 3.5.0
  - 3.5.1
  #- devel
warnings_are_errors: true
sudo: required
apt_packages:
  #- libfftw3-dev
bioc_packages:
  - qvalue
  - GO.db
  - ggtree
  - topGO
r_packages:
  - covr
  - ape
  - phangorn
r_github_packages:
  - surh/AMOR
  - sgearle/bugwas/bugwas
after_success:
  - Rscript -e 'library(covr); codecov()'
